// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "account": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=account/design
// --out=$(GOPATH)/src/account
// --version=v1.3.0

package app
